FROM node as builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# CMD ["npm","run","start"]
RUN npm run build

FROM nginx

COPY --from=builder /app/dist/client /usr/share/nginx/html
